TARGET   = xSCL.far-plug-mb
OBJFILES = ../shared/debug.o ../shared/registry.o ../shared/widestring.o \
           xSCL.o manager_del.o manager_get.o manager_key.o manager_put.o manager_tools.o manager.o tools.o detector.o
           
include ../include.mk