TARGET   = xCreate.far-plug-mb
OBJFILES = ../shared/registry.o ../shared/widestring.o \
           xCreate.o tools.o creator.o Make_fdd.o Make_fdi.o Make_scl.o Make_td.o Make_trd.o Make_udi.o
           
include ../include.mk
