TARGET   = xTRD.far-plug-mb
OBJFILES = ../shared/debug.o ../shared/registry.o ../shared/widestring.o \
           xTRD.o manager.o detector.o FmtReader.o tools.o mngr_tools.o mngr_dir.o mngr_del.o mngr_get.o mngr_put.o   mngr_key.o  \
           Formats/TRD/trd.o \
           Formats/FDD/fdd.o Formats/FDD/filer.o \
           Formats/FDI/fdi.o Formats/FDI/filer.o \
           Formats/TELEDISK/teledisk.o Formats/TELEDISK/filer.o Formats/TELEDISK/td_tools.o 
           #          Formats/UDI/udi.o Formats/UDI/filer.o \

include ../include.mk
